# Generated by Django 5.1.2 on 2024-10-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorshipchat',
            old_name='sender',
            new_name='participant_one',
        ),
        migrations.RenameField(
            model_name='mentorshipchat',
            old_name='recipient',
            new_name='participant_two',
        ),
    ]
