# Generated by Django 5.1.2 on 2024-10-30 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_sender_mentorshipchat_participant_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career_journey',
            field=models.TextField(blank=True, help_text='A brief overview of the career journey.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Contact phone number.', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text="User's current location.", max_length=255),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the achievement.', max_length=255)),
                ('date_achieved', models.DateField(help_text='Date when the achievement was obtained.')),
                ('description', models.TextField(blank=True, help_text='Description of the achievement.')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the certificate.', max_length=255)),
                ('institution', models.CharField(help_text='Institution that issued the certificate.', max_length=255)),
                ('date_issued', models.DateField(help_text='Date the certificate was issued.')),
                ('description', models.TextField(blank=True, help_text='Optional description of the certificate.')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the skill.', max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Job title.', max_length=255)),
                ('company_name', models.CharField(help_text='Name of the company.', max_length=255)),
                ('start_date', models.DateField(help_text='Start date of employment.')),
                ('end_date', models.DateField(blank=True, help_text='End date of employment (leave blank if current).', null=True)),
                ('responsibilities', models.TextField(blank=True, help_text='Responsibilities in this role.')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='core.profile')),
            ],
        ),
    ]
